using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Synapse.Server.Extensibility.Utility
{
    public class ApiController
    {
        public string Name { get; set; }
        public string RoutePrefix { get; set; }
        public bool CreateHelloApiMethod { get; set; } = true;
        public bool CreateWhoAmIApiMethod { get; set; } = true;
        public bool CreateClassFileOnly { get; set; } = false;
        public List<ApiMethod> ApiMethods { get; set; } = new List<ApiMethod>();

        public virtual string ToClassCode()
        {
            string code = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Web.Http;

using Synapse.Services;


namespace Synapse.Custom
{
    [RoutePrefix( ~~RoutePrefix~~ )]
    public class ~~Name~~Controller : ApiController
    {
~~ApiMethods~~
    }
}";

            if( string.IsNullOrWhiteSpace( Name ) )
                Name = $"SynapseCustomApi{Utilities.GetSystemGeneratedName()}";
            if( string.IsNullOrWhiteSpace( RoutePrefix ) )
                RoutePrefix = Name.ToLower();
            if( ApiMethods == null )
                ApiMethods = new List<ApiMethod>();
            if( CreateWhoAmIApiMethod )
                ApiMethods.Insert( 0, new ApiMethod { Name = "WhoAmI", ReturnStub = "\"hi\"" } );
            if( CreateHelloApiMethod )
                ApiMethods.Insert( 0, new ApiMethod { Name = "Hello", ReturnStub = "\"hi\"" } );

            code = Regex.Replace( code, "~~RoutePrefix~~", $"\"{RoutePrefix}\"" );
            code = Regex.Replace( code, "~~Name~~", Name );
            code = Regex.Replace( code, "~~ApiMethods~~", ApiMethods.ToClassCode() );

            return code;
        }

        public static ApiController CreateSample()
        {
            ApiController sample = new ApiController { Name = "Custom" };
            sample.ApiMethods.Add( ApiMethod.CreateSample() );

            return sample;
        }
    }
}