//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synapse.Server.Extensibility.Utility.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Synapse.Server.Extensibility.Utility.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Net.Http;
        ///using System.Web.Http;
        ///using Synapse.Core;
        ///using Synapse.Services;
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ControllerCode {
            get {
                return ResourceManager.GetString("ControllerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         #region DAL API Methods
        ///        static object _dalConfig = null;
        ///
        ///        public ~~Name~~Controller()
        ///        {
        ///            GetDalConfig();
        ///        }
        ///        void GetDalConfig()
        ///        {
        ///            if( _dalConfig == null )
        ///            {
        ///                string thisAssmName = System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
        ///                _dalConfig = ExtensibilityUtility.GetExecuteControllerInstance( null, null, null ).GetCustomAssemblyConfig( thisAssmName );
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DalApiCode {
            get {
                return ResourceManager.GetString("DalApiCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///
        ///using LiteDB;
        ///
        ///using Synapse.Core.Utilities;
        ///
        ///namespace Synapse.Custom
        ///{
        ///    public class ~~class~~Dal
        ///    {
        ///        private static string _db = @&quot;~~class~~.db&quot;;
        ///        private const string __table = &quot;~~class~~List&quot;;
        ///
        ///        public ~~class~~Dal() { }
        ///        public ~~class~~Dal(object rawConfig)
        ///        {
        ///            if( rawConfig == null )
        ///                throw new ArgumentNullException( &quot;rawConfig&quot; );
        ///
        ///            _db = DatabaseConnect [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DalCode {
            get {
                return ResourceManager.GetString("DalCode", resourceCulture);
            }
        }
    }
}
